# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election2000', '0002_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
