# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election2000', '0009_auto_20170419_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='ballots_cast',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='circuit',
            name='ballots_given_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='circuit',
            name='ballots_invalid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='circuit',
            name='ballots_valid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='circuit',
            name='eligible',
            field=models.IntegerField(default=0),
        ),
    ]
