# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election2000', '0010_auto_20170419_1133'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='circuit',
            unique_together=set([('number', 'district', 'gmina')]),
        ),
    ]
