# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election2000', '0011_auto_20170419_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voivodeship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='voivodeship',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='election2000.Voivodeship'),
            preserve_default=False,
        ),
    ]
