# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election2000', '0012_auto_20170419_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='document',
            field=models.FileField(default=None, null=True, upload_to='documents'),
        ),
    ]
